"use client";

import { useState } from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import ResumeGeneratorForm from '@/components/resume/ResumeGeneratorForm';
import ResumeRevampForm from '@/components/resume/ResumeRevampForm';
import ResumeEditor from '@/components/resume/ResumeEditor';
import LoadingSpinner from '@/components/LoadingSpinner';
import type { GenerateResumeFormData, RevampResumeFormData } from '@/lib/schemas';
import { generateResumeAction, revampResumeAction } from '@/app/actions/resumeActions';
import { useToast } from "@/hooks/use-toast";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Wand2, FileEdit } from 'lucide-react';

type ResumeResult = {
  content: string;
  suggestions?: string[];
  title: string;
  description: string;
} | null;

export default function HomePage() {
  const [resumeResult, setResumeResult] = useState<ResumeResult>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isRevamping, setIsRevamping] = useState(false);
  const { toast } = useToast();

  const handleGenerateSubmit = async (data: GenerateResumeFormData) => {
    setIsGenerating(true);
    setResumeResult(null);
    try {
      const result = await generateResumeAction(data);
      if (result.success && result.resume) {
        setResumeResult({
          content: result.resume,
          title: "AI Generated Resume",
          description: "Your resume has been generated by AI. Review and edit below."
        });
        toast({ title: "Success!", description: "Resume generated successfully." });
      } else {
        toast({ variant: "destructive", title: "Error", description: result.error || "Failed to generate resume." });
      }
    } catch (error) {
      toast({ variant: "destructive", title: "Error", description: "An unexpected error occurred." });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleRevampSubmit = async (data: RevampResumeFormData) => {
    setIsRevamping(true);
    setResumeResult(null);
    try {
      const result = await revampResumeAction(data);
      if (result.success && result.revampedResume) {
        setResumeResult({
          content: result.revampedResume,
          suggestions: result.suggestions,
          title: "AI Revamped Resume",
          description: "Your resume has been revamped by AI. Review the changes and suggestions."
        });
        toast({ title: "Success!", description: "Resume revamped successfully." });
      } else {
        toast({ variant: "destructive", title: "Error", description: result.error || "Failed to revamp resume." });
      }
    } catch (error) {
      toast({ variant: "destructive", title: "Error", description: "An unexpected error occurred." });
    } finally {
      setIsRevamping(false);
    }
  };

  return (
    <div className="space-y-8">
      <Card className="text-center bg-gradient-to-r from-primary/10 via-accent/10 to-secondary/10 p-8 rounded-xl shadow-xl">
        <CardHeader>
          <CardTitle className="text-4xl font-extrabold tracking-tight lg:text-5xl text-primary">
            Welcome to ResumAI
          </CardTitle>
          <CardDescription className="mt-4 text-lg text-foreground/80 max-w-2xl mx-auto">
            Craft your perfect resume with the power of Artificial Intelligence. Generate a new resume from scratch or revamp your existing one with smart suggestions.
          </CardDescription>
        </CardHeader>
      </Card>

      <Tabs defaultValue="generate" className="w-full">
        <TabsList className="grid w-full grid-cols-2 md:w-1/2 mx-auto">
          <TabsTrigger value="generate" className="py-3 text-base">
            <Wand2 className="mr-2 h-5 w-5" /> Generate New
          </TabsTrigger>
          <TabsTrigger value="revamp" className="py-3 text-base">
            <FileEdit className="mr-2 h-5 w-5" /> Revamp Existing
          </TabsTrigger>
        </TabsList>
        <TabsContent value="generate" className="mt-6">
          <ResumeGeneratorForm onSubmit={handleGenerateSubmit} isSubmitting={isGenerating} />
        </TabsContent>
        <TabsContent value="revamp" className="mt-6">
          <ResumeRevampForm onSubmit={handleRevampSubmit} isSubmitting={isRevamping} />
        </TabsContent>
      </Tabs>

      {(isGenerating || isRevamping) && (
        <div className="flex justify-center items-center mt-8 p-8 bg-card rounded-lg shadow-md">
          <LoadingSpinner size={48} />
          <p className="ml-4 text-lg text-primary animate-pulse">
            {isGenerating ? "Generating your resume, please wait..." : "Revamping your resume, this may take a moment..."}
          </p>
        </div>
      )}

      {resumeResult && (
        <ResumeEditor 
          content={resumeResult.content} 
          suggestions={resumeResult.suggestions}
          title={resumeResult.title}
          description={resumeResult.description}
        />
      )}
    </div>
  );
}
